### ISSUE TITLE
接入网易云跟帖

### ISSUE THREAD

**Issue by shinyYangYang** [twoyao/beautiful-hexo#11]
我尝试接入网易云跟贴在博客中,  但是试了很多方法还是没能解决.  您能给我指导下不?

**Comment by twoyao** [comment]
我添加了网易云的支持(layout/partial/netease.jade)， 你需要更新下主题
```
cd themes/beautiful-hexo && git pull origin master
```

在主题配置(beautiful-hexo/_config.yml) 中设置`comment.netease.productKey` 这个productKey从网易云更贴后台获取。**测试需要修改host名称，保证和hostname和后台设置一直，否则不会显示**，见readme

**Comment by shinyYangYang** [comment]
谢谢您. 完美解决了我的问题. 🌺🌺
