### ISSUE TITLE
IndieWeb and beautiful-hexo

### ISSUE THREAD

**Issue by gigitux** [twoyao/beautiful-hexo#15]
My idea is to make this template compatible with Indieweb standards. What do you think about it?

Some links: https://indieweb.org/
https://indiewebify.me/

**Comment by twoyao** [comment]
Probably not, since I am not familiar with Indieweb. Pull requests welcome.

**Comment by gigitux** [comment]
Great, I will work on it :)

Il 21 lug 2017 6:25 AM, "twoyao" <notifications@github.com> ha scritto:
