### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by MicahRCM** [twoyao/beautiful-hexo#16]
Having no problem cloning other themes, but when I get to this:
git clone --depth 1 git@github.com:twoyao/beautiful-hexo.git themes/beautiful-hexo

I get the following error:
https://gyazo.com/215f6baf1317a8c5223f791e3b1f4b96

Any ideas?

**Comment by twoyao** [comment]
use `git clone --depth 1 https://github.com/twoyao/beautiful-hexo.git themes/beautiful-hexo`

**Comment by MicahRCM** [comment]
Perfect
