### ISSUE TITLE
Small screens/mobile issue

### ISSUE THREAD

**Issue by JacksonJS** [twoyao/beautiful-hexo#2]
At 365 width the index title and motto disappear. This is disastrous for mobile.

**Comment by twoyao** [comment]
@JacksonJS  I don't have a 365px width device, but i tested on chrome. It seems ok .

![image](https://cloud.githubusercontent.com/assets/3994717/17076347/d7dc885c-50e2-11e6-83c1-c2cf757d9fe6.png)

Would you please post a screenshot as demonstration? thanks

**Comment by JacksonJS** [comment]
Devtools before and after:

![beautiful_hexo_full](https://cloud.githubusercontent.com/assets/18562629/17080482/82dc1922-50e6-11e6-8420-d2b4124674d2.png)

![beautiful_hexo_smallscreen](https://cloud.githubusercontent.com/assets/18562629/17080484/93b07efa-50e6-11e6-9ac8-98ab4b352bef.png)

From phone:
![image](https://cloud.githubusercontent.com/assets/18562629/17080496/f0aed7d2-50e6-11e6-9e48-93c2242c42a5.png)

**Comment by twoyao** [comment]
It's a feature of beautiful-jekyll. I create a new branch `no-hiding` change the threshold to 325px. Feel free to modify main.css to meet your needs.

see https://github.com/twoyao/beautiful-hexo/commit/5aafc524aff252a8af1efc65d4c464ead6afa86e

**Comment by twoyao** [comment]
https://github.com/twoyao/beautiful-hexo/commit/de493c2ce21e5253cdaadc37958da7db393a1c25

**Comment by JacksonJS** [comment]
Thanks a lot, that fixed the issue!
