### ISSUE TITLE
Could you add latex support?

### ISSUE THREAD

**Issue by UnknowsBetter** [twoyao/beautiful-hexo#21]
I don't know how to add it manually :(

**Comment by UnknowsBetter** [comment]
I tried, but failed

**Comment by twoyao** [comment]
Sorry I have no time to maintain this project, you have to try it yourself.

**Comment by UnknowsBetter** [comment]
> Sorry I have no time to maintain this project, you have to try it yourself.

OK， anyway thanks for what a brilliant work you have done.
