### ISSUE TITLE
文章过长后面的文字会变乱码

### ISSUE THREAD

**Issue by flyingtime** [twoyao/beautiful-hexo#6]
文章内容太长文字会变成乱码，而且后面的评论信息、上下翻译也都没有了。将md改成UTF8就好了。

**Comment by XuankangLin** [comment]
求问「将md改成UTF8就好了」是在哪里标明为 UTF8？我也遇到了类似的问题，太长的文章就被截断了，后头的文字、评论也都不显示了

**Comment by twoyao** [comment]
@flyingtime 说应该是指将md博客的文件格式改为UTF8编码。是博客正文还是首页被截断？如果是首页，会根据`<!-- more -->`截断生成摘要。参考下[这里](https://raw.githubusercontent.com/twoyao/beautiful-hexo/post/source/_posts/dh-intro.md)

**Comment by XuankangLin** [comment]
@twoyao 谢谢，我指的是正文里被截断，一句话还没有显示完就停下来了，后边的 disqus 插件等等也就没有了。我后来发现甚至用默认主题的时候也可能出现这个问题，所以应该不是 beautiful-hexo 的原因了。我猜想是由于浏览器 JavaScript 报错而停止加载了，因为有一个 console log:
```
[Violation] Forced reflow while executing JavaScript took 399ms
```
我在 hexo 的 repo 里也报了这个问题了 <https://github.com/hexojs/hexo/issues/2601>，有意思的是，我在 localhost 中遇到这个问题，在 push 到 github pages 之后反而没有了。
